// This file is autogenerated by Whook
// Do not try to change it in place
/* eslint-disable @typescript-eslint/ban-types */
declare interface paths {
  '/v26/delay': {
    get: operations['getDelay'];
  };
  '/v26/diagnostic': {
    get: operations['getDiagnostic'];
  };
  '/v26/openAPI': {
    get: operations['getOpenAPI'];
  };
  '/v26/{pathParam1}/{pathParam2}': {
    get: operations['getParameters'];
  };
  '/v26/time': {
    get: operations['getTime'];
    put: operations['putTime'];
  };
  '/v26/crons/{cronName}/run': {
    post: operations['postCronRun'];
  };
  '/v26/echo': {
    put: operations['putEcho'];
  };
  '/v26/stream': {
    put: operations['putEchoedStream'];
  };
  '/v26/ping': {
    get: operations['getPing'];
  };
}
declare interface operations {
  postDelayCallback: {
    responses: {
      204: object;
    };
    parameters: {
      query: {
        duration: components['parameters']['duration'];
      };
    };
  };
  getDelay: {
    callbacks: {
      DelayCallback: components['callbacks']['DelayCallback'];
    };
    responses: {
      204: object;
    };
    parameters: {
      query: {
        duration: components['parameters']['duration'];
        callbackUrl?: components['schemas']['URISchema'];
      };
    };
  };
  getDiagnostic: {
    responses: {
      200: components['responses']['Diagnostic'];
    };
  };
  getOpenAPI: {
    responses: {
      200: {
        body: object;
      };
    };
  };
  getParameters: {
    responses: {
      200: {
        body: {
          aHeader?: components['schemas']['Boolean'];
          aMultiHeader?: [
            components['schemas']['Number'],
            components['schemas']['Number'],
          ];
          pathParam1?: components['schemas']['Number'];
          pathParam2?: components['schemas']['String'];
          queryParam?: components['schemas']['Strings'];
        };
      };
    };
    parameters: {
      path: {
        pathParam1: components['parameters']['pathParam1'];
        pathParam2: components['parameters']['pathParam2'];
      };
      query: {
        queryParam: components['parameters']['queryParam'];
      };
      headers: {
        'a-header'?: components['schemas']['Boolean'];
        aMultiHeader?: components['schemas']['Numbers'];
      };
    };
  };
  getTime: {
    responses: {
      200: {
        body: components['schemas']['TimeSchema'];
      };
    };
  };
  putTime: {
    requestBody: components['schemas']['TimePayload'];
    responses: {
      201: {
        body: number;
      };
    };
  };
  postCronRun: {
    requestBody: components['schemas']['AnyObject'];
    responses: {
      204: object;
    };
    parameters: {
      path: {
        cronName: components['schemas']['String'];
      };
      query: {
        date: components['parameters']['date'];
      };
    };
  };
  putEcho: {
    requestBody: components['requestBodies']['Echo'];
    responses: {
      200: components['responses']['Echo'];
    };
  };
  putEchoedStream: {
    requestBody: components['requestBodies']['Stream'];
    responses: {
      201: components['responses']['Stream'];
    };
  };
  getPing: {
    responses: {
      200: {
        body: {
          pong?: 'pong';
        };
      };
    };
  };
}
declare interface components {
  callbacks: {
    DelayCallback: {
      '{$request.query.callbackUrl}': {
        post: operations['postDelayCallback'];
      };
    };
  };
  parameters: {
    duration: components['schemas']['Number'];
    pathParam1: components['schemas']['Number'];
    pathParam2: components['schemas']['String'];
    queryParam: components['schemas']['Strings'];
    date: components['schemas']['Date'];
  };
  responses: {
    Diagnostic: {
      body: {
        transactions: {
          [pattern: string]: unknown;
        };
      };
    };
    Echo: {
      body: components['schemas']['Echo'];
    };
    Stream: {
      body: components['schemas']['Stream'];
    };
  };
  requestBodies: {
    Echo: components['schemas']['Echo'];
    Stream: components['schemas']['Stream'];
  };
  schemas: {
    URISchema: string;
    Boolean: boolean;
    Number: number;
    Numbers: components['schemas']['Number'][];
    String: string;
    Strings: components['schemas']['String'][];
    TimeSchema: {
      currentDate?: string;
    };
    AnyObject: {
      [pattern: string]: unknown;
    };
    Date: string;
    Echo: {
      echo: string;
    };
    Stream: NodeJS.ReadableStream;
    TimePayload: {
      time: number;
      isFixed?: boolean;
    };
    ExampleSchema: {
      message: string;
      delay: number;
    };
  };
}
