// This file is autogenerated by Whook
// Do not try to change it in place
/* eslint-disable @typescript-eslint/ban-types */
declare namespace API {
  export namespace GetDelay {
    export type Output = Responses.$204;
    export type Input = {
      readonly duration: Parameters.Duration;
    };
    export namespace Responses {
      export type $204 = Components.Responses.getDelayResponse204<204>;
    }
    export namespace Parameters {
      export type Duration = Components.Parameters.Duration;
    }
  }
  export namespace GetDiagnostic {
    export type Output = Responses.$200;
    export type Input = {};
    export namespace Responses {
      export type $200 = Components.Responses.Diagnostic<200>;
    }
  }
  export namespace GetOpenAPI {
    export type Output = Responses.$200;
    export type Input = {};
    export namespace Responses {
      export type $200 = Components.Responses.getOpenAPIResponse200<200>;
    }
  }
  export namespace GetParameters {
    export type Output = Responses.$200;
    export type Input = {
      readonly aHeader?: Parameters.AHeader;
      readonly aMultiHeader?: Parameters.AMultiHeader;
      readonly pathParam1: Parameters.PathParam1;
      readonly pathParam2: Parameters.PathParam2;
      readonly queryParam: Parameters.QueryParam;
    };
    export namespace Responses {
      export type $200 = Components.Responses.getParametersResponse200<200>;
    }
    export namespace Parameters {
      export type AHeader = Components.Parameters.GetParameters3;
      export type AMultiHeader = Components.Parameters.GetParameters4;
      export type PathParam1 = Components.Parameters.PathParam1;
      export type PathParam2 = Components.Parameters.PathParam2;
      export type QueryParam = Components.Parameters.QueryParam;
    }
  }
  export namespace GetTime {
    export type Output = Responses.$200;
    export type Input = {};
    export namespace Responses {
      export type $200 = Components.Responses.getTimeResponse200<200>;
    }
  }
  export namespace PutTime {
    export type Body = Components.RequestBodies.PutTimeRequestBody;
    export type Output = Responses.$200;
    export type Input = {
      readonly body: Body;
    };
    export namespace Responses {
      export type $200 = Components.Responses.putTimeResponse200<200>;
    }
  }
  export namespace PutEcho {
    export type Body = Components.RequestBodies.Echo;
    export type Output = Responses.$200;
    export type Input = {
      readonly body: Body;
    };
    export namespace Responses {
      export type $200 = Components.Responses.Echo<200>;
    }
  }
  export namespace GetPing {
    export type Output = Responses.$200;
    export type Input = {};
    export namespace Responses {
      export type $200 = Components.Responses.getPingResponse200<200>;
    }
  }
}
declare namespace Components {
  export namespace RequestBodies {
    export type Echo = Components.Schemas.Echo;
    export type PutTimeRequestBody =
      Components.Schemas.RequestBodiesputTimeRequestBodyBody0;
  }
  export namespace Parameters {
    export type Duration = number;
    export type PathParam1 = number;
    export type PathParam2 = string;
    export type GetParameters3 = boolean;
    export type QueryParam = string[];
    export type GetParameters4 = number[];
  }
  export namespace Responses {
    export type getDelayResponse204<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body?: unknown;
    };
    export type Diagnostic<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.ResponsesDiagnosticBody0;
    };
    export type Echo<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.Echo;
    };
    export type getOpenAPIResponse200<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.ResponsesgetOpenAPIResponse200Body0;
    };
    export type getParametersResponse200<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.ResponsesgetParametersResponse200Body0;
    };
    export type getTimeResponse200<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.TimeSchema;
    };
    export type putTimeResponse200<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.ResponsesputTimeResponse200Body0;
    };
    export type getPingResponse200<S extends number> = {
      readonly status: S;
      readonly headers?: {
        readonly [name: string]: unknown;
      };
      readonly body: Components.Schemas.ResponsesgetPingResponse200Body0;
    };
  }
  export namespace Schemas {
    export type Echo = {
      echo: string;
    };
    export type RequestBodiesputTimeRequestBodyBody0 = {
      time?: number;
      isFixed?: boolean;
    };
    export type ResponsesDiagnosticBody0 = {
      transactions: {
        [pattern: string]: unknown;
      };
    };
    export type ResponsesgetOpenAPIResponse200Body0 = {};
    export type ResponsesgetParametersResponse200Body0 = {
      aHeader?: boolean;
      aMultiHeader?: number[];
      pathParam1?: number;
      pathParam2?: string;
      queryParam?: string[];
    };
    export type TimeSchema = {
      currentDate?: string;
    };
    export type ResponsesputTimeResponse200Body0 = number;
    export type ResponsesgetPingResponse200Body0 = {
      pong?: 'pong';
    };
  }
}
