import { basename } from 'node:path';
import { type WhookCronsDefinitionsService } from '@whook/whook';

export type GNUWhookCronSchedule = {
  name: string;
  rule: string;
};

export const CRON_DATE_COMMAND = '$(date -u +\\%Y-\\%m-\\%dT\\%H:\\%M:\\%SZ)';
export const SYSTEMD_DATE_COMMAND = '$(date -u +%Y-%m-%dT%H:%M:%SZ)';

export function getCronSchedules(
  CRONS_DEFINITIONS: WhookCronsDefinitionsService,
): GNUWhookCronSchedule[] {
  return Object.keys(CRONS_DEFINITIONS).flatMap((name) =>
    CRONS_DEFINITIONS[name].module.definition.schedules.map((schedule) => ({
      name,
      rule: schedule.rule,
    })),
  );
}

export function buildCrontabContent(
  cronSchedules: GNUWhookCronSchedule[],
  {
    APP_ENV,
    PROJECT_DIR,
    LOGS_DIR,
  }: {
    APP_ENV: string;
    PROJECT_DIR: string;
    LOGS_DIR: string;
  },
): string {
  const logFile = `${LOGS_DIR}/cron.log`;
  const entries = cronSchedules.map(
    ({ name, rule }) =>
      `${rule} cd "${PROJECT_DIR}" && APP_ENV="${APP_ENV}" NODE_ENV=production ./node_modules/.bin/whook cronRun --name "${name}" --date "${CRON_DATE_COMMAND}" >> "${logFile}" 2>&1`,
  );

  return [
    '# Generated by @whook/gnu-linux',
    '# Install with: crontab < whook.crontab',
    '# Replay once with: /bin/sh -lc \'APP_ENV="<env>" NODE_ENV=production ./node_modules/.bin/whook cronRun --name "<cronName>" --date "$(date -u +%Y-%m-%dT%H:%M:%SZ)"\'',
    ...entries,
    '',
  ].join('\n');
}

export function buildSystemdCronServiceContent(
  cronName: string,
  {
    APP_ENV,
    PROJECT_DIR,
    LOGS_DIR,
  }: {
    APP_ENV: string;
    PROJECT_DIR: string;
    LOGS_DIR: string;
  },
): string {
  return `[Unit]
Description=Run Whook cron ${cronName}
After=network.target

[Service]
Type=oneshot
WorkingDirectory=${PROJECT_DIR}
ExecStart=/bin/sh -lc 'APP_ENV="${APP_ENV}" NODE_ENV=production ./node_modules/.bin/whook cronSchedule --name "${cronName}" --startDate "$(date -u -d "-2 minute" +%Y-%m-%dT%H:%M:%SZ)" --endDate "${SYSTEMD_DATE_COMMAND}"'
StandardOutput=append:${LOGS_DIR}/cron-${cronName}.log
StandardError=append:${LOGS_DIR}/cron-${cronName}.log
`;
}

export function buildSystemdCronTimerContent(serviceName: string): string {
  return `[Unit]
Description=Run ${serviceName} every minute

[Timer]
OnCalendar=*-*-* *:*:00
Persistent=true
Unit=${serviceName}.service

[Install]
WantedBy=timers.target
`;
}

export function buildSystemdDaemonServiceContent({
  APP_ENV,
  PROJECT_DIR,
  LOGS_DIR,
  appName = basename(PROJECT_DIR),
}: {
  APP_ENV: string;
  PROJECT_DIR: string;
  LOGS_DIR: string;
  appName?: string;
}): string {
  return `[Unit]
Description=Whook daemon (${appName})
After=network.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_DIR}
Environment=APP_ENV=${APP_ENV}
Environment=NODE_ENV=production
ExecStart=/bin/sh -lc './node_modules/.bin/whook'
Restart=always
RestartSec=5
StandardOutput=append:${LOGS_DIR}/daemon.log
StandardError=append:${LOGS_DIR}/daemon.log

[Install]
WantedBy=multi-user.target
`;
}

export function buildLogrotateConfigContent(logsDir: string): string {
  return `${logsDir}/*.log {
  daily
  rotate 14
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
}
`;
}

export function buildLogrotateCronContent(logrotateConfigPath: string): string {
  return `0 0 * * * /usr/sbin/logrotate ${logrotateConfigPath}\n`;
}

export function buildLogrotateSystemdServiceContent(
  logrotateConfigPath: string,
): string {
  return `[Unit]
Description=Rotate Whook logs

[Service]
Type=oneshot
ExecStart=/usr/sbin/logrotate ${logrotateConfigPath}
`;
}

export function buildLogrotateSystemdTimerContent(serviceName: string): string {
  return `[Unit]
Description=Rotate Whook logs daily

[Timer]
OnCalendar=daily
Persistent=true
Unit=${serviceName}.service

[Install]
WantedBy=timers.target
`;
}
